# # Missing Value Imputation by Simple Impute <br/>

# Problem : 
An Fruit Selling company wants to analyze their sales data. However there are certain missing values in the Prodict Line , Item Sold, Sales and Profit. Here we have used Simple Impueter to fill the NA value for Numeric missing value and applied Most frequest method function to fill the missing value for Categorical Data. <br/> 




In [1]:
pwd

'C:\\Users\\User\\Git-Hup Files\\Feature Eng'

In [2]:
cd C:\Users\User\Desktop\Anindita Mitra\Machine Learning\EDA

C:\Users\User\Desktop\Anindita Mitra\Machine Learning\EDA


In [3]:
#Import all the library
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.impute import SimpleImputer

In [4]:
#load the dataset
df = pd.read_csv("Fruits_Sales.csv")

In [5]:
df.shape

(13, 4)

In [6]:
df.head()

PRODUCTLINE  ITEMSSOLD    SALES   Profit
0       Mango       30.0    850.0    560.0
1       Mango       34.0      NaN    400.0
2      Banana       41.0  12001.0      NaN
3      Banana        NaN  19000.0  18000.0
4      Banana       49.0  27000.0  23000.0

In [7]:
#Lets check the data types
df.dtypes

PRODUCTLINE     object
ITEMSSOLD      float64
SALES          float64
Profit         float64
dtype: object

# Numerical Missing Value

In [8]:
#Assigning an oject which has only the numerical value 
num = df.select_dtypes(include=["int64","float64"]).columns

In [9]:
num

Index(['ITEMSSOLD', 'SALES', 'Profit'], dtype='object')

In [10]:
#Checking individual data frame respectively
#df1 : Numerical Value
df[num].isnull().sum()

ITEMSSOLD    3
SALES        4
Profit       6
dtype: int64

# Applying Simple Inputer

In [11]:
#Here implementing mean startegy 
imputer_mean =  SimpleImputer(strategy="mean")

In [12]:
#Apply fit method to x which has the numerical missing value of Product Line and Sales
imputer_mean.fit(df[num])

SimpleImputer(add_indicator=False, copy=True, fill_value=None,
              missing_values=nan, strategy='mean', verbose=0)

In [13]:
#these are the missing value calculated based on Product Line and Sales
imputer_mean.statistics_

array([   36.        , 10316.77777778,  8780.        ])

In [14]:
#applying transform method to fill the missing value of Product Line with 35.13333 and Sales with 10259.69491525 whereever
#the data is missing
imputer_mean.transform(df[num])

array([[3.00000000e+01, 8.50000000e+02, 5.60000000e+02],
       [3.40000000e+01, 1.03167778e+04, 4.00000000e+02],
       [4.10000000e+01, 1.20010000e+04, 8.78000000e+03],
       [3.60000000e+01, 1.90000000e+04, 1.80000000e+04],
       [4.90000000e+01, 2.70000000e+04, 2.30000000e+04],
       [3.60000000e+01, 3.00000000e+03, 8.78000000e+03],
       [2.90000000e+01, 4.00000000e+03, 8.78000000e+03],
       [4.80000000e+01, 1.03167778e+04, 4.50000000e+03],
       [3.40000000e+01, 8.00000000e+03, 8.78000000e+03],
       [3.60000000e+01, 9.00000000e+03, 8.00000000e+03],
       [3.60000000e+01, 1.00000000e+04, 8.78000000e+03],
       [2.30000000e+01, 1.03167778e+04, 7.00000000e+03],
       [3.60000000e+01, 1.03167778e+04, 8.78000000e+03]])

In [15]:
#Converting array to a dataframe
df[num] = imputer_mean.transform(df[num])

In [16]:
df[num].isnull().sum()

ITEMSSOLD    0
SALES        0
Profit       0
dtype: int64

# Senario 2 :
If any constant value needs to be filled insted of mean

In [17]:
imputer_mean2 =  SimpleImputer(strategy="constant", fill_value=27)

In [18]:
#Apply fit method to x which has the numerical missing value of Product Line and Sales
imputer_mean2.fit(df[num])

SimpleImputer(add_indicator=False, copy=True, fill_value=27, missing_values=nan,
              strategy='constant', verbose=0)

In [19]:
imputer_mean2.statistics_

array([27., 27., 27.])

In [20]:
#applying transform method to fill the missing value of Product Line with 35.13333 and Sales with 10259.69491525 whereever
#the data is missing
imputer_mean2.transform(df[num])

array([[3.00000000e+01, 8.50000000e+02, 5.60000000e+02],
       [3.40000000e+01, 1.03167778e+04, 4.00000000e+02],
       [4.10000000e+01, 1.20010000e+04, 8.78000000e+03],
       [3.60000000e+01, 1.90000000e+04, 1.80000000e+04],
       [4.90000000e+01, 2.70000000e+04, 2.30000000e+04],
       [3.60000000e+01, 3.00000000e+03, 8.78000000e+03],
       [2.90000000e+01, 4.00000000e+03, 8.78000000e+03],
       [4.80000000e+01, 1.03167778e+04, 4.50000000e+03],
       [3.40000000e+01, 8.00000000e+03, 8.78000000e+03],
       [3.60000000e+01, 9.00000000e+03, 8.00000000e+03],
       [3.60000000e+01, 1.00000000e+04, 8.78000000e+03],
       [2.30000000e+01, 1.03167778e+04, 7.00000000e+03],
       [3.60000000e+01, 1.03167778e+04, 8.78000000e+03]])

In [21]:
#Converting array to a dataframe
df[num] = imputer_mean2.transform(df[num])

In [22]:
df[num].isnull().sum()

ITEMSSOLD    0
SALES        0
Profit       0
dtype: int64

# Categorical Missing Value Imputation

In [23]:
#Assigning an oject which has only the categorical value 
cat = df.select_dtypes(include=["object"]).columns

In [24]:
df.dtypes

PRODUCTLINE     object
ITEMSSOLD      float64
SALES          float64
Profit         float64
dtype: object

In [25]:
cat

Index(['PRODUCTLINE'], dtype='object')

In [26]:
df[cat].isnull().sum()

PRODUCTLINE    2
dtype: int64

In [30]:
 imputer_mean3 =  SimpleImputer(strategy="most_frequent")

In [31]:
imputer_mean3

SimpleImputer(add_indicator=False, copy=True, fill_value=None,
              missing_values=nan, strategy='most_frequent', verbose=0)

In [32]:
imputer_mean3.fit(df[cat])

SimpleImputer(add_indicator=False, copy=True, fill_value=None,
              missing_values=nan, strategy='most_frequent', verbose=0)

In [33]:
imputer_mean3.statistics_

array(['Banana'], dtype=object)

In [34]:
imputer_mean3.transform(df[cat])

array([['Mango'],
       ['Mango'],
       ['Banana'],
       ['Banana'],
       ['Banana'],
       ['Banana'],
       ['Banana'],
       ['Banana'],
       ['Banana'],
       ['Banana'],
       ['Banana'],
       ['Banana'],
       [' ']], dtype=object)

In [35]:
df[cat] = imputer_mean3.transform(df[cat])

In [36]:
df[cat].isnull().sum()

PRODUCTLINE    0
dtype: int64